config/routes.rb
Rails.application.routes.draw do
  get 'answers/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?  

  devise_for :users

  resources :users
  resources :questions do
    resources :favorites, only: [:create, :destroy]
    resources :useful_answers, only: [:create, :destroy]    
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  has_many :useful_answers
  has_many :users, through: :useful_answers
  has_many :questions, through: :useful_answers
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :answer, optional: true

  validates_uniqueness_of :question_id, scope: :user_id
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user  

  has_many :useful_answers
  has_many :users, through: :useful_answers
  has_many :answers, through: :useful_answers    

  def self.ransackable_attributes(auth_object = nil)
    %w[title content]
  end

end

app/models/useful_answer.rb
class UsefulAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable, :confirmable  
  has_many :questions
  has_many :favorites
  has_many :favorite_questions, through: :favorites, source: :question  

  has_many :useful_answers
  has_many :questions, through: :useful_answers
  has_many :answers, through: :useful_answers  

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user! # ログイン済みのユーザーのみアクセスを許可
  before_action :check_admin # 管理者権限を持っているユーザーのみアクセスを許可
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private

  # 管理者権限を持っているかチェックするメソッド
  def check_admin
    redirect_to root_path, alert: "管理者権限が必要です" unless current_user.admin?
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, only: [:create, :edit, :update, :destroy]  

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
    if @answer.save
      redirect_to @question, notice: "回答を投稿しました。"
    else
      render :new
    end

  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to @question
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:content, :user_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :branch])

  end  

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @question = Question.find(params[:question_id])
    favorite = current_user.favorite_questions.new(question: @question, answer: @question.answers.first.body)
    if favorite.save
      redirect_to @question, notice: 'Question was successfully favorited.'
    else
      # handle error
    end
  end

  def destroy
    @question = Favorite.find(params[:id]).question
    current_user.favorite_questions.delete(@question)
    redirect_to @question  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 

  def index
    @questions = Question.all.includes(:user)

    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true)
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.includes(:user)
    @answer = Answer.new
    @current_user = current_user    
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      redirect_to @question, notice: "質問を投稿しました。"
    else
      render :new
    end
  end


  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end  

  def question_params
    params.require(:question).permit(:category_id, :title, :content)
  end  

end

app/controllers/useful_answers_controller.rb
class UsefulAnswersController < ApplicationController
end

app/controllers/usefuls_answer_controller.rb
before_action :authenticate_user!

def create
  @useful_answer = current_user.useful_answers.build(useful_answer_params)
  if @useful_answer.save
    redirect_back(fallback_location: root_path, notice: "回答が役に立ったと投票しました")
  else
    redirect_back(fallback_location: root_path, alert: "回答の評価に失敗しました")
  end
end

def destroy
  @useful_answer = current_user.useful_answers.find_by(answer_id: params[:answer_id])
  if @useful_answer.destroy
    redirect_back(fallback_location: root_path, notice: "回答の評価を取り消しました")
  else
    redirect_back(fallback_location: root_path, alert: "回答の評価取り消しに失敗しました")
  end
end

private

def useful_answer_params
  params.permit(:answer_id)
end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/useful_answers_helper.rb
module UsefulAnswersHelper
end

app/views/questions/index.html.erb
<h1>質問一覧</h1>

<%= search_form_for @q do |f| %>
  <%= f.label :title_cont, "Title" %>
  <%= f.search_field :title_cont %>
  <%= f.label :content_cont, "Content" %>
  <%= f.search_field :content_cont %>
  <%= f.submit "Search" %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>No</th>
      <th>質問方</th>
      <th>カテゴリー</th>
      <th>タイトル</th>
      <th>内容</th>
      <th>ステータス</th>  
      <th>お気に入り</th>              
      <th>質問詳細ページ</th>                            
    </tr>
  </thead>
  <tbody>
    <% @questions.each_with_index do |question, index| %>        
      <tr>
        <td><%= index + 1 %></td>  
        <td><%= question.user.name %></td>
        <td><%= question.category.name %></td>
        <td><%= question.title %></td>
        <td><%= question.content %></td>
        <td><%= question.status ? "終了" : "受付中" %></td> 
        <td>
        <% if user_signed_in? && current_user && current_user.favorited?(question) %>        
          お気に入り        
          <% end %>
        </td>
        <td><%= link_to 'Show', question %></td>                
      </tr>                                    
    <% end %>      
  </tbody>    
</table>

<%= link_to '新たに質問する', new_question_path %>

app/views/questions/new.html.erb
<h1>新しい質問を投稿</h1>

<%= form_with model: @question, local: true do |form| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>     
    </div>
<% end %>

<div class="form-group">

<%= form.label :タイトル %>
<%= form.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
<%= form.label :内容 %>
    <%= form.text_area :content, class: "form-control" %>
</div>

<div class="form-group">
<%= form.submit "質問を投稿する", class: "btn btn-primary" %>
</div>
<% end %>


<%= link_to '質問一覧に戻る', questions_path %>

app/views/questions/show.html.erb
<h2><%= @question.title %></h2>

<p><%= @question.content %></p>

<table>
  <tr>
    <th>回答</th>
    <th>ユーザー名</th>
  </tr>    
  <% @question.answers.each do |answer| %>
    <tr>
      <td><%= answer.content %></td>
      <td><%= answer.user ? answer.user.name : current_user.name %></td>
    </tr>
  <% end %>
</table>

<% if @question.status == "closed" %>
  <p><strong>この質問は終了しました。</strong></p>
<% elsif current_user == @question.user %>
  <%= link_to "終了する", close_question_path(@question), method: :patch, class: "btn btn-primary" %>
<% end %>

<% if user_signed_in? %>
  <% if @answer.useful?(current_user) %>
    <%= form_for(current_user.useful_answers.find_by(answer_id: @answer.id),
                html: { method: :delete },
                url: useful_answer_path(current_user.useful_answers.find_by(answer_id: @answer.id))) do |f| %>
      <%= f.submit "役に立たない", class: "btn btn-danger" %>
    <% end %>
  <% else %>
    <%= form_with(url: useful_answers_path(answer_id: @answer.id)) do |f| %>
      <%= f.hidden_field :answer_id, value: @answer.id %>
      <%= f.submit "役に立った", class: "btn btn-success" %>
    <% end %>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <% if @question.favorited?(current_user) %>
    <%= form_for(current_user.favorites.find_by(question_id: @question.id),
                html: { method: :delete },
                url: favorite_path(current_user.favorites.find_by(question_id: @question.id))) do |f| %>
      <%= f.submit "お気に入りから外す", class: "btn btn-danger" %>
    <% end %>
  <% else %>
    <%= form_with(url: favorites_path(question_id: @question.id)) do |f| %>
      <%= f.hidden_field :question_id, value: @question.id %>
      <%= f.submit "お気に入りに登録する", class: "btn btn-primary" %>
    <% end %>
  <% end %>
<% end %>

<h3>回答を投稿する</h3>
<%= form_with(model: [ @question, @question.answers.build ], local: true) do |form| %>
  <% if @question.errors.any? || @question.answers.any? { |a| a.errors.any? } %>  
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count + @question.answers.sum { |a| a.errors.count }, "error") %> prohibited this question from being saved:</h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        <% @question.answers.each do |answer| %>
          <% answer.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :content, "回答" %>
    <%= form.text_area :content, class: "form-control", rows: 5 %>
  </div>
  <%= form.submit "投稿する", class: "btn btn-primary" %>
<% end %>